### PR TITLE
Add monitor for process' message queue size

### PR DESCRIPTION
**Pull request by mkaszubowski**
Since message queue size is one of the most important metric, which often can tell you if something is wrong, it's quite nice to have it here as well.

The `MonitorMessageQueue` code is quite similar for the `MonitorMemory`, so we could possibly abstract it a bit, but I decided to follow "three strikes and then refactor" rule and not do this now. What do you think?

### CODE REVIEW

**Comment by derekkraan** [comment]
:trophy: for submitting a PR in record time!

I agree with your rationale for not refactoring yet. Better to keep it dumb and easy for now, we can refactor later if we have more examples that look like this one.

I just added CircleCI integration, can you rebase to trigger that from this branch? Then I don't have to check out your code and run the tests locally :joy:

**Comment by mkaszubowski** [comment]
I'm not sure if the CI is triggered. Only rebasing didn't seem to do anything so I've added a new commit, but I still cannot see anything. Should I see it on github, or is it only visible from CircleCI?

**Comment by derekkraan** [comment]
Hmm weird doesn't seem to be getting triggered. I see that you've rebased correctly so it's not that. I'll just run your tests locally and call it a day.

**Comment by mkaszubowski** [comment]
Ok, I've rebased once more to squash the commits into one :)

**Comment by derekkraan** [comment]
I needed to turn on a setting on CircleCI, it should work for future PRs.

**Pull request merged**
